name: Build Web
on:
  push:
    branches:
      - master
jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run build
        run: |
          npm build
